// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Company struct {
	CompanyID uuid.UUID
	Name      string
}

type CompanySnapshot struct {
	CompanySnapshotID uuid.UUID
	Name              string
	OfferIds          []uuid.UUID
}

type Offer struct {
	OfferID         uuid.UUID
	ExternalID      uuid.UUID
	Title           string
	JobSite         string
	ExperienceLevel string
	WorkplaceType   string
	OfferStatus     string
	CompanyID       uuid.UUID
	MinimalWage     float32
	MaximalWage     float32
	Slug            string
	ExpiredAt       pgtype.Timestamptz
	PublishedAt     pgtype.Timestamptz
}

type Skill struct {
	SkillID  uuid.UUID
	Name     string
	Variants []string
}

type SkillSnapshot struct {
	SkillSnapshotID uuid.UUID
	Name            string
	OfferIds        []uuid.UUID
}
