spring:
  application:
    name: JobJarApi

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Fwj85+7j#N)=
    name: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

http-clients:
  JUST_JOIN_IT:
    headers:
      version: 2
    url:
      base: api.justjoin.it
      version: v2
      path: user-panel/offers
    params:
      sortBy: published
      perPage: 100
