spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: JobJarApi

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
#    dynamic: false

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Fwj85+7j#N)=
    name: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

logging:
  file:
    name: logs/api.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger - %msg%n"
  level:
    root: info

http-clients:
  JUST_JOIN_IT:
    headers:
      version: 2
    url:
      base: api.justjoin.it
      version: v2
      path: user-panel/offers
    params:
      sortBy: newest
      perPage: 100
  THE_PROTOCOL:
    headers:
      cookie: ${THE_PROTOCOL_COOKIE}
      x-xsrf-token: ${THE_PROTOCOL_XSRF_TOKEN}
      content-type: application/json
    url:
      base: apus-api.theprotocol.it
      path: offers/_search
    params:
      pageNumber: 1
      orderby.field: LastRefreshDateUtc
      pageSize: 50
