// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCompany = `-- name: CreateCompany :exec
INSERT INTO companies(company_id, name)
VALUES($1, $2)
`

type CreateCompanyParams struct {
	CompanyID uuid.UUID
	Name      string
}

// :::: COMPANY ::::
func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) error {
	_, err := q.db.Exec(ctx, createCompany, arg.CompanyID, arg.Name)
	return err
}

const createCompanySnapshot = `-- name: CreateCompanySnapshot :exec
INSERT INTO company_snapshots(company_snapshot_id, name, offer_ids)
VALUES($1, $2, $3)
`

type CreateCompanySnapshotParams struct {
	CompanySnapshotID uuid.UUID
	Name              string
	OfferIds          []uuid.UUID
}

// :::: COMPANY_SNAPSHOTS::::
func (q *Queries) CreateCompanySnapshot(ctx context.Context, arg CreateCompanySnapshotParams) error {
	_, err := q.db.Exec(ctx, createCompanySnapshot, arg.CompanySnapshotID, arg.Name, arg.OfferIds)
	return err
}

type CreateOfferParams struct {
	OfferID         uuid.UUID
	ExternalID      uuid.UUID
	Title           string
	JobSite         string
	ExperienceLevel string
	WorkplaceType   string
	OfferStatus     string
	CompanyID       uuid.UUID
	MinimalWage     float32
	MaximalWage     float32
	Slug            string
	ExpiredAt       pgtype.Timestamptz
	PublishedAt     pgtype.Timestamptz
}

const createSkillSnapshot = `-- name: CreateSkillSnapshot :exec
INSERT INTO skill_snapshots(skill_snapshot_id, name, offer_ids)
VALUES($1, $2, $3)
`

type CreateSkillSnapshotParams struct {
	SkillSnapshotID uuid.UUID
	Name            string
	OfferIds        []uuid.UUID
}

// :::: SKILL_SNAPSHOTS ::::
func (q *Queries) CreateSkillSnapshot(ctx context.Context, arg CreateSkillSnapshotParams) error {
	_, err := q.db.Exec(ctx, createSkillSnapshot, arg.SkillSnapshotID, arg.Name, arg.OfferIds)
	return err
}

type CreateSkillSnapshotsParams struct {
	SkillSnapshotID uuid.UUID
	Name            string
	OfferIds        []uuid.UUID
}

const getCompanyByName = `-- name: GetCompanyByName :one
SELECT company_id, name FROM companies
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetCompanyByName(ctx context.Context, name string) (Company, error) {
	row := q.db.QueryRow(ctx, getCompanyByName, name)
	var i Company
	err := row.Scan(&i.CompanyID, &i.Name)
	return i, err
}

const getCompanySnapshotByName = `-- name: GetCompanySnapshotByName :one
SELECT company_snapshot_id, name, offer_ids FROM company_snapshots
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetCompanySnapshotByName(ctx context.Context, name string) (CompanySnapshot, error) {
	row := q.db.QueryRow(ctx, getCompanySnapshotByName, name)
	var i CompanySnapshot
	err := row.Scan(&i.CompanySnapshotID, &i.Name, &i.OfferIds)
	return i, err
}

const getSkillByVariant = `-- name: GetSkillByVariant :one
SELECT skill_id, name, variants FROM skills
WHERE ($1::text = ANY (variants)) LIMIT 1
`

// :::: SKILLS ::::
func (q *Queries) GetSkillByVariant(ctx context.Context, variant string) (Skill, error) {
	row := q.db.QueryRow(ctx, getSkillByVariant, variant)
	var i Skill
	err := row.Scan(&i.SkillID, &i.Name, &i.Variants)
	return i, err
}

const getSkillByVariants = `-- name: GetSkillByVariants :many
SELECT skill_id, name, variants FROM skills
WHERE variants @> ARRAY[$1]
`

func (q *Queries) GetSkillByVariants(ctx context.Context, variants []string) ([]Skill, error) {
	rows, err := q.db.Query(ctx, getSkillByVariants, variants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(&i.SkillID, &i.Name, &i.Variants); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSkillSnapshotByName = `-- name: GetSkillSnapshotByName :one
SELECT skill_snapshot_id, name, offer_ids FROM skill_snapshots
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetSkillSnapshotByName(ctx context.Context, name string) (SkillSnapshot, error) {
	row := q.db.QueryRow(ctx, getSkillSnapshotByName, name)
	var i SkillSnapshot
	err := row.Scan(&i.SkillSnapshotID, &i.Name, &i.OfferIds)
	return i, err
}

const getSkillSnapshotsByNames = `-- name: GetSkillSnapshotsByNames :many
SELECT skill_snapshot_id, name, offer_ids FROM skill_snapshots
WHERE (name = ANY ($1::text[]))
`

func (q *Queries) GetSkillSnapshotsByNames(ctx context.Context, names []string) ([]SkillSnapshot, error) {
	rows, err := q.db.Query(ctx, getSkillSnapshotsByNames, names)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkillSnapshot
	for rows.Next() {
		var i SkillSnapshot
		if err := rows.Scan(&i.SkillSnapshotID, &i.Name, &i.OfferIds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompanySnapshot = `-- name: UpdateCompanySnapshot :exec
UPDATE company_snapshots
SET offer_ids = $2
WHERE company_snapshot_id = $1
`

type UpdateCompanySnapshotParams struct {
	CompanySnapshotID uuid.UUID
	OfferIds          []uuid.UUID
}

func (q *Queries) UpdateCompanySnapshot(ctx context.Context, arg UpdateCompanySnapshotParams) error {
	_, err := q.db.Exec(ctx, updateCompanySnapshot, arg.CompanySnapshotID, arg.OfferIds)
	return err
}

const updateSkillSnapshot = `-- name: UpdateSkillSnapshot :exec
UPDATE skill_snapshots
SET offer_ids = $2
WHERE skill_snapshot_id = $1
`

type UpdateSkillSnapshotParams struct {
	SkillSnapshotID uuid.UUID
	OfferIds        []uuid.UUID
}

func (q *Queries) UpdateSkillSnapshot(ctx context.Context, arg UpdateSkillSnapshotParams) error {
	_, err := q.db.Exec(ctx, updateSkillSnapshot, arg.SkillSnapshotID, arg.OfferIds)
	return err
}
