// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertOffer = `-- name: InsertOffer :exec
INSERT INTO offers(offer_id, external_id, title, job_site, experience_level, workplace_type, offer_status, company_id, minimal_wage, maximal_wage, slug, expired_at, published_at)
VALUES($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type InsertOfferParams struct {
	OfferID         uuid.UUID
	ExternalID      uuid.UUID
	Title           string
	JobSite         string
	ExperienceLevel string
	WorkplaceType   string
	OfferStatus     string
	CompanyID       uuid.UUID
	MinimalWage     float32
	MaximalWage     float32
	Slug            string
	ExpiredAt       pgtype.Timestamptz
	PublishedAt     pgtype.Timestamptz
}

func (q *Queries) InsertOffer(ctx context.Context, arg InsertOfferParams) error {
	_, err := q.db.Exec(ctx, insertOffer,
		arg.OfferID,
		arg.ExternalID,
		arg.Title,
		arg.JobSite,
		arg.ExperienceLevel,
		arg.WorkplaceType,
		arg.OfferStatus,
		arg.CompanyID,
		arg.MinimalWage,
		arg.MaximalWage,
		arg.Slug,
		arg.ExpiredAt,
		arg.PublishedAt,
	)
	return err
}
